### ISSUE TITLE
Blank screen after submitting a song with a collaborator tagged

### ISSUE THREAD

**Issue by rufusdumont** [pablomurasaki/song-a-day-for-a-month#25]
There's an issue when transmitting a song with a collaborator tag. After the user uploads the song, it doesn't go immediately to the song with the revoke option after it's uploaded. It just goes to a blank screen (at least this is what happens on my computer in both Safari and Chrome - Ryan could not replicate this on his computer). Once I refresh the page, the song + revoke option does appear. Can we make it so that the song + revoke page appears immediately after submitting the song?

**Comment by ebbnormal** [comment]
@pablomurasaki I think what is going on is that the song is transmitted successfully but the request to get lastTransmission via the function call `lastTransmission` fails but we don’t handle the errror case for the angular `$.loaded` therefore we just hang out on a white screen since we have set transmitted to true and the ng if now shows the new song but it hasn’t loaded so it is white

**Comment by ebbnormal** [comment]
We can probably just say a simple error either in an alert or in a div saying “ error connection to server. Please refresh the page “ or something

**Comment by pablomurasaki** [comment]
i simply have it reloading the page on successful transmission

**Comment by pablomurasaki** [comment]
well after seeing @ebbnormal 's comment i removed the z index which proved to be a better solution than a hard reset

**Comment by ebbnormal** [comment]
@pablomurasaki hmm should we just add a condition to the `ngIf` of that div saying `ngIf="formerCondition && !transmitted` or something? because otherwise if we just remove the z-index then it might revert the feature of click the div to dismiss the ui-select dropdown menu ..
